### ISSUE TITLE
Help : (most) commands have no effect !

### ISSUE THREAD

**Issue by hutou** [xarthurx/taskwarrior.vim#1]
Hi,
I just installed your plugin and cannot understand why, but most commands do nothing.
As an example, 'A' does allow annotation, but 'a' has no effect !
I probably missed something important.
Please help !

**Comment by xarthurx** [comment]
Hi, would you please list the commands that do not work?
I need more info to identify the problem.

**Comment by hutou** [comment]
I started to test from a minimal .vimrc (vim version is 8.1) and very small set of test tasks.
The plugin has several malfunctions :
- Commands which do not seem to have any effect are : 'o', 'm', 'M', 'R', 'p', 'H', 'L', 'J', 'K', 'B'
- Some commands ('d', space, 'c' notably) show a delay of 1 or 2 seconds before execution.
- Command 'a' (new task) needs to be followed by CR to continue (or ESC to quit). Typed characters are not echoed for the current field, but are assigned to the next ! I tried the original version from BlindFS which does not show such weird behavior. [Edit] BlindFS version also have this behavior: so, is it a vim version problem ?

So, in my opinion, in its current state, the plugin is hardly usable.
Can you reproduce these issues ?

**Comment by xarthurx** [comment]
@hutou 

Hi, Are you on Linux or Windows?
I cannot reproduce these issues.
I'm using Neovim on Windows and everything works smoothly for my needs (otherwise I'd not release this fork).

Yes, I changed the mechanism of inputting info so that I can cancel a task anytime (the original one doesn't allow that.) 

Would you be able to test on Neovim?

**Comment by xarthurx** [comment]
I guess it is because of the mechanism that how the two `VIM` take chars. 
The current input is activated by `getchar()` instead of the original `getline()`.

**Comment by xarthurx** [comment]
I updated the readme until this issue is solved.

**Comment by hutou** [comment]
I am on Linux (Arch 64 - GNome, both up to date)
I tried neovim : the plugin also has issues, but not exactly the same as with vim.

Here are the main differences from vim :
- the 'a', 'p', 'H', 'L', 'J', 'K', 'B' command are Ok
- 'D' command tries to execute, but fails with the message

> :!task 52 delete                                                                                                                                                                                                          
> Delete task 52 'test task'? (yes/no) Task not deleted.
> Deleted 0 tasks
> shell returned 1
> Press ENTER or type command to continue

- Like the 'D' command, the 'u' command does not allow the user to confirm or not, so it fails:

> ...
> The undo command is not reversible.  Are you sure you want to revert to the previous state? (yes/no) No changes made.
> Press ENTER or type command to continue

- Also, with both vim and nvim, cursor movement (line down or up) is not fluid (erratic moves up or down)

As the plugin is ok on Neovim / Windows, I suspect a compatibility problem with Linux.

**Comment by xarthurx** [comment]
@hutou  Thank you for the testing.

For `D` and `u`, these two actions are kind of legacy of the original plugin, which I haven't got time to fix totally.
These two are using different mechanisms than others.

For the `D` action, if you type Y, the task should be deleted. No?
For the `u` action, yes, no confirmation for now but you can redo the action. Probably I'll cancel the popup info.

The above two issues can be fixed relatively easy.

I'm not sure about the fluid issue currently, as it seems to be fine here.
But the bottleneck of the whole plugin is the speed of calling `SHELL task` command, for this, I cannot do too much about it.

So I guess the main issue is between vim/neovim now. 
I may test further if I setup a virtual machine sometime this/next month.

Will let you know once I finish.

**Comment by albertwh1te** [comment]
I have checked this issue. Neovim works perfectly. Maybe @hutou  should give it a try.

**Comment by xarthurx** [comment]
Thank you @MarkWh1te  for the check.
I currently have no plan to support vim. Only Neovim is supported now.
