### ISSUE TITLE
Adds 2.5 seconds to vim startuptime

### ISSUE THREAD

**Issue by bongoman** [xarthurx/taskwarrior.vim#2]
I noticed the same issue with the blindfs repo.

`vim --startuptime vim.log` reveals:

`023.785  000.052  000.052: sourcing /Users/richard/.vim/pack/minpac/start/taskpaper.vim/           ftdetect/taskpaper.vim`
 
`2783.951  2760.021  2760.021: sourcing /Users/richard/.vim/pack/minpac/start/taskwarrior.vim/      plugin/taskwarrior.vim`

Adds over 2.5 seconds to startup time.

**Comment by xarthurx** [comment]
Hi there.

Sorry, I don't have vim installed so cannot verify the issue.
On my machine, with the newest `neovim`, it shows:

`1024.092  259.012  259.012: sourcing C:\Users\xxxx\AppData\Local\nvim\plugged\taskwarrior.vim\plugin\taskwarrior.vim`
which is 0.25 sec, and almost not feeling it.

I'm currently occupied with some urgent stuff and cannot do more tests.
 If you'd like to help, I'll appreciate it.

**Comment by albertwh1te** [comment]
`145.522  092.075  092.075: sourcing /Users/mark/.vim/bundle/taskwarrior.vim/plugin/taskwarrior.vim`
I  use vim with verison 8.1

**Comment by xarthurx** [comment]
Closing since the plugin doesn't support Vim8.
