### ISSUE TITLE
Edit currently highlighted field/task in a new (Neo)vim buffer

### ISSUE THREAD

**Issue by maxigaz** [xarthurx/taskwarrior.vim#3]
It would be great to have the ability to edit the field or task the cursor is currently on in a new Neovim buffer instead of using the statusline.

A request for such a feature was [brought up](https://github.com/blindFS/vim-taskwarrior/issues/92) for the original version of the plugin and Vim a while ago. I wonder if it’s possible to implement it now in Neovim (or even Vim 8+).

**Comment by xarthurx** [comment]
Hi, I don't think Neovim currently have the functionality, after a brief search about it.
But if you could prove I'm wrong, I'm happy to implement it. :)
