### ISSUE TITLE
Task move to an unpredictable location when stopped

### ISSUE THREAD

**Issue by clobrano** [xarthurx/taskwarrior.vim#8]
First of all, thanks for this awesome plugin, and for keeping up with the maintanance.

I noticed that when starting a new task, the selected task goes to the top of the list, but when stopped it goes back to its position, and might be hard to find again.
Would it be possible to either:
- keep the task in its original position when started
- move the cursor to the task position when stopped

Thanks

**Comment by xarthurx** [comment]
Do you mean using `+/-` to start/stop the task?
On my machine, the task will not move.

Could you provide more info?

**Comment by clobrano** [comment]
Hi, sorry but I am not using it anymore, I do remember that with my  system the task moved on top of the list pressing +/-
